name: Hello world
on:
  push:
    branches:
     -main
jobs:
  first_hello_world_job:
    runs_on: ubuntu_latest
    steps:
      - name: checkout one
        uses: actions/checkout@v3
      - name: print message
        run: echo "hello world Ga Testing"
   
